<!doctype html>
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>CD2019</title> <link rel="stylesheet" type="text/css" href="./../static/cmsimply.css">
<script src="tipuesearch_content.js"></script>
<script src="./../static/jquery.js"></script>
<link rel="stylesheet" href="./../static/tipuesearch/css/tipuesearch.css">
<script src="./../static/tipuesearch/tipuesearch_set.js"></script>
<script src="./../static/tipuesearch/tipuesearch.min.js"></script>

<script type="text/javascript" src="./../static/syntaxhighlighter/shCore.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushJScript.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushJava.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushPython.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushSql.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushXml.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushPhp.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushLua.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCpp.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCss.js"></script>
<script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCSharp.js"></script>
<link type="text/css" rel="stylesheet" href="./../static/syntaxhighlighter/css/shCoreDefault.css"/>
<script type="text/javascript">SyntaxHighlighter.all();</script>

<!-- for LaTeX equations 暫時不用
<script src="https://scrum-3.github.io/web/math/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script>
<script type="text/javascript">
init_mathjax = function() {
    if (window.MathJax) {
        // MathJax loaded
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
            },
            displayAlign: 'left', // Change this to 'center' to center equations.
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}}
            }
        });
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    }
}
init_mathjax();
</script>
-->
<!-- 暫時不用
<script src="./../static/fengari-web.js"></script>
<script type="text/javascript" src="./../static/Cango-13v08-min.js"></script>
<script type="text/javascript" src="./../static/CangoAxes-4v01-min.js"></script>
<script type="text/javascript" src="./../static/gearUtils-05.js"></script>
-->
<!-- for Brython 暫時不用
<script src="https://scrum-3.github.io/web/brython/brython.js"></script>
<script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"></script>
-->
<style>
img.with_border {
    border: 3px solid red;
}
</style>

<script type="text/javascript">
/*shorthand of $(document).ready(function(){};); */
$(function(){
    $("ul.topmenu> li:has(ul) > a").append('<div class="arrow-right"></div>');
    $("ul.topmenu > li ul li:has(ul) > a").append('<div class="arrow-right"></div>');
});
function doSearch() {
     $('#tipue_search_input').tipuesearch({
        newWindow: true, minimumLength: 2
     });
}
$(document).ready(doSearch);
</script>

</head><header><h1>2019 Spring 協同產品設計實習</h1> <confmenu>
<ul>
<li><a href="index.html">Home</a></li>
<li><a href="sitemap.html">Site Map</a></li>
<li><a href="./../reveal/index.html">reveal</a></li>
<li><a href="./../blog/index.html">blog</a></li>

</ul>
</confmenu></header>
<div class='container'><nav><ul id='css3menu1' class='topmenu'><div class="tipue_search_group"><input style="width: 6vw;" type="text" name="q" id="tipue_search_input" pattern=".{2,}" title="Press enter key to search" required></div><li><a href='Introduction.html'>Introduction</a><ul><li><a href='Future Jobs Report.html'>Future Jobs Report</a></li></ul><li><a href='實習任務.html'>實習任務</a><ul><li><a href='實習任務一.html'>實習任務一</a><ul><li><a href='建立可攜程式系統.html'>建立可攜程式系統</a><li><a href='第一週分組程式.html'>第一週分組程式</a><li><a href='Git Book 摘要.html'>Git Book 摘要</a><li><a href='Github 自學.html'>Github 自學</a><li><a href='w1取分項目.html'>w1取分項目</a></li></ul><li><a href='實習任務二.html'>實習任務二</a><ul><li><a href='V-rep Introduction.html'>V-rep Introduction</a><li><a href='BubbleRob.html'>BubbleRob</a><li><a href='BubbleRob1.html'>BubbleRob1</a></li></ul><li><a href='實習任務三.html'>實習任務三</a><li><a href='實習任務四.html'>實習任務四</a><li><a href='實習任務五.html'>實習任務五</a><li><a href='實習任務六.html'>實習任務六</a></li></ul><li><a href='協同設計.html'>協同設計</a><li><a href='Onshape.html'>Onshape</a><ul><li><a href='BOMs.html'>BOMs</a></li></ul><li><a href='FreeCAD.html'>FreeCAD</a><ul><li><a href='FreeCAD STL.html'>FreeCAD STL</a></li></ul><li><a href='V-rep.html'>V-rep</a><ul><li><a href='V-rep Tutorial.html'>V-rep Tutorial</a><li><a href='v-rep ref.html'>v-rep ref</a></li></ul><li><a href='Webots.html'>Webots</a><ul><li><a href='Webots doc.html'>Webots doc</a></li></ul></nav><section><div id="tipue_search_content">BOMs << <a href='BOMs.html'>Previous</a> <a href='FreeCAD STL.html'>Next</a> >> FreeCAD STL<br /><h1>FreeCAD</h1>
<p><a href="https://drive.google.com/file/d/149LTLypC9eeStWfrlLceAkozZq4F8A_r/view?usp=sharing">FreeCAD 0.18.7z for Windows 10 64 位元 下載</a></p>
<p>上述系統內建 python36.exe, 若與 wscite 合用, 需要 Python 3.6 版次中的 pythonw.exe (<a href="./../downloads/pythonw_36.7z">下載 pythonw_36.7z</a>)</p>
<p>測試程式:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import FreeCAD, Part
import FreeCADGui

FreeCADGui.showMainWindow()
mw=FreeCADGui.getMainWindow()
mw.hide()

obj=Part.makeCone(10,8,10)
doc = FreeCAD.newDocument()
Part.show(obj)

view = FreeCADGui.getDocument(doc.Name).activeView()
view.setAnimationEnabled(False)
view.viewAxometric()
view.fitAll()

# It's important not to use Qt's QGLFramebufferObject because it crashes when no GUI is shown
# but Qt's QGLPixelBuffer still works.
par=FreeCAD.ParamGet("User parameter:BaseApp")
grp=par.GetGroup("Preferences/Document")
grp.SetBool("DisablePBuffers",False)

view.saveImage('crystal.png',800,600,'Current')
FreeCAD.closeDocument(doc.Name)</pre>
<p>建立零件, 轉為 stl  檔案:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import FreeCAD
import Part
import Mesh
shape = Part.makeCone(10,8,10)
doc = App.newDocument('Doc')
pf = doc.addObject("Part::Feature","MyShape")
pf.Shape = shape
Mesh.export([pf], 'my_cone.stl')</pre>
<p>利用布林運算建立零件後, 轉為 stl 檔案:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import FreeCAD, FreeCADGui, Part , Mesh
from FreeCAD import Base
import math
steps=360 #number of polyline segments
dang=math.radians(360/steps) #step angle
e=10 #eccentricity
r=60 #radius
ang=0 #start anle
z=0 #line z coordinate
halfw=r+e+20
halfh=r+e+20

for i in range(steps): #make many lines and connect they in wire (polyline, epitrochoid)
    if i==0: #for first line
        x1=e*math.cos(3*ang)+r*math.cos(ang) #coords for line startpoint
        y1=e*math.sin(3*ang)+r*math.sin(ang)
        ang=dang 
        x2=e*math.cos(3*ang)+r*math.cos(ang) #coords for line endpoint
        y2=e*math.sin(3*ang)+r*math.sin(ang)
        seg=Part.makeLine((x1,y1,z),(x2,y2,z))
        wire2=Part.Wire([seg])
        x1=x2
        y1=y2
    else: 
        x2=e*math.cos(3*ang)+r*math.cos(ang)
        y2=e*math.sin(3*ang)+r*math.sin(ang)
        seg=Part.makeLine((x1,y1,z),(x2,y2,z))
        wire2=Part.Wire([wire2,seg])
        x1=x2
        y1=y2
    ang=ang+dang #increment angle

edge1 = Part.makeLine((-halfw,halfh,0), (halfw,halfh,0)) #lines needed to create rectangle
edge2 = Part.makeLine((halfw,halfh,0), (halfw,-halfh,0))
edge3 = Part.makeLine((halfw,-halfh,0), (-halfw,-halfh,0))
edge4 = Part.makeLine((-halfw,-halfh,0), (-halfw,halfh,0))
wire1 = Part.Wire([edge1,edge2,edge3,edge4]) #rectangle
face1 = Part.Face(wire1) #face from rectangle
face2=Part.Face(wire2) #face from epitrochoid http://en.wikipedia.org/wiki/Epitrochoid
diff = face1.cut(face2) #boolean cut epitrochoid from rectangle
ext=diff.extrude(Base.Vector(0,0,30)) #extrude the cut (face)
#Part.show(ext) #show extrude in FreeCAD window
doc = App.newDocument('Doc')
pf = doc.addObject("Part::Feature","MyShape")
pf.Shape = ext
Mesh.export([pf], 'my_ext.stl')</pre>
<p></p>
<br />BOMs << <a href='BOMs.html'>Previous</a> <a href='FreeCAD STL.html'>Next</a> >> FreeCAD STL</div></section></div></body></html>